[run]
  deadline = "10m"
  tests = true

[linters]
  disable-all = true
  enable = [
    "deadcode",
    "depguard",
    "goconst",
    "gocyclo",
    "gocritic",
    "gosec",
    "gosimple",
    "ineffassign",
    "maligned",
    "misspell",
    "nakedret",
    "staticcheck",
    "structcheck",
    "typecheck",
    "unconvert",
    "unparam",
    "varcheck",
    "vet",
    "vetshadow",
  ]
